In [12]:
import numpy
numpy.__version__

'1.21.5'

In [2]:
L=list(range(10))  # or range(0->start,10->end,2->step)
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
L.sort(reverse=True)
L

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [15]:
type(L[0])

int

In [13]:
L[::2]

[9, 7, 5, 3, 1]

In [7]:
L2=[str(c) for c in L]

In [9]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2)

list

In [11]:
type(L2[0])

str

In [4]:
L3=[True,"2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
L4=[L2,L3,"ghi"]
L4

[['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
 [True, '2', 3.0, 4],
 'ghi']

In [10]:
L4[0][2] #acessing second element from first list(nested list)

'2'

In [16]:
t1=(1,2)  #tuples

In [17]:
t1

(1, 2)

In [ ]:
t1[0]=5  #can't change values in tuples

In [24]:
d1={"key1":1,
   "key2":2,
   "key3":3}
   #dictionaries
d1
d1["key1"]

1

In [15]:
#fixed type arrays
import array
L = list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
import numpy as np

In [28]:
#integer array
np.array([1,4,2,5,3])  #inputting list in array

array([1, 4, 2, 5, 3])

In [29]:
n1=np.array([3.14,4,2,3]) #making each float as one is float

In [30]:
type(n1)

numpy.ndarray

In [31]:
n1.dtype

dtype('float64')

In [19]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
# nested list resolved in multidimensional arrays
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
#creating array from scratch
#create a length 10 integer array filled with zeroes
#import numpy as np
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#create a 3X5 floating point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
#creating array filled with linear sequence
#starting with 0, ending at 20, stepping by 2
#similar like range() funvc
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#create a 3X3 array of uniformly distributed
#random values between 0 and 1
np.random.random((3,3))

array([[0.19018663, 0.91484524, 0.09840186],
       [0.60786395, 0.2392279 , 0.29849579],
       [0.3541794 , 0.01997301, 0.81089046]])

In [14]:
#create a 3X3 array of uniformly distributed
#random values with mean 0 and SD 1
np.random.normal(0,1,(3,3))

array([[ 0.20970866,  0.74197403,  0.69557733],
       [ 1.34438668,  1.43637156,  0.89382369],
       [-1.23738108,  2.21337056,  1.22744195]])

In [17]:
#create a 3X3 array of random integers in interval [0,10)
np.random.randint(0,10,(3,3))

array([[2, 4, 0],
       [4, 4, 2],
       [1, 6, 8]])

In [18]:
#create a 3X3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#create uninitialised array of 3 integers
#values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [21]:
#numpy standard data types
print("yash")

yash


In [25]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [27]:
#numpy array attributes
import numpy as np
np.random.seed(0) #seed for reproducibility
x1=np.random.randint(10, size=6) #1D array
x2=np.random.randint(10, size=(3,4)) #2D array
x3=np.random.randint(10, size=(3,4,5))

In [28]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [29]:
print("dtype:",x3.dtype)

dtype: int32


In [30]:
print("item size: ", x3.itemsize,"bytes")
print("nbytes: ", x3.nbytes, "bytes")

item size:  4 bytes
nbytes:  240 bytes


In [31]:
#array indexing 
x1

array([5, 0, 3, 3, 7, 9])

In [32]:
x1[0]

5

In [33]:
x1[4]

7

In [34]:
x1[-3]

3

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x2[0,2]

2

In [37]:
x2[0,3]

4

In [38]:
x2[3,0]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [33]:
#array slicing
#x[]
#x[start:stop:step]
#1D subarrays
import numpy as np
x=np.arange(10)    #like range in list arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x.shape

(10,)

In [3]:
x[:5]

array([0, 1, 2, 3, 4])

In [4]:
x[5:]

array([5, 6, 7, 8, 9])

In [5]:
x[4:7]

array([4, 5, 6])

In [6]:
x[::3]

array([0, 3, 6, 9])

In [7]:
x[1::2]

array([1, 3, 5, 7, 9])

In [8]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
x[5::-2]

array([5, 3, 1])

In [36]:
x7=np.random.rand(3,3)
x7

array([[0.40915978, 0.37762286, 0.37560494],
       [0.62621923, 0.22442334, 0.95193243],
       [0.17772926, 0.07079114, 0.7344285 ]])

In [11]:
#multidimensional subarray
x2=np.random.randint(10, size=(3,4)) #2D array
x2

array([[4, 9, 8, 0],
       [2, 1, 0, 0],
       [8, 2, 2, 6]])

In [12]:
x2[:2, :3]

array([[4, 9, 8],
       [2, 1, 0]])

In [13]:
x2[:3, ::2]

array([[4, 8],
       [2, 0],
       [8, 2]])

In [14]:
x2[::-1, ::-1]

array([[6, 2, 2, 8],
       [0, 0, 1, 2],
       [0, 8, 9, 4]])

In [15]:
#accessing array rows and columns
print(x2[:,0])

[4 2 8]


In [16]:
print(x2[0,:])

[4 9 8 0]


In [17]:
print(x2[0])

[4 9 8 0]


In [18]:
#subarrays with no copy views
print(x2)

[[4 9 8 0]
 [2 1 0 0]
 [8 2 2 6]]


In [19]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[4 9]
 [2 1]]


In [20]:
x2

array([[4, 9, 8, 0],
       [2, 1, 0, 0],
       [8, 2, 2, 6]])

In [26]:
x2_sub[0,0]=99
print(x2_sub)
x2

[[99  9]
 [ 2  1]]


array([[99,  9,  8,  0],
       [ 2,  1,  0,  0],
       [ 8,  2,  2,  6]])

In [23]:
#creating copies of array
x2_sub_copy=x2[:2,:2].copy()
x2_sub_copy

array([[99,  9],
       [ 2,  1]])

In [24]:
x2_sub_copy[0,0]=50
x2_sub_copy

array([[50,  9],
       [ 2,  1]])

In [25]:
x2

array([[99,  9,  8,  0],
       [ 2,  1,  0,  0],
       [ 8,  2,  2,  6]])

In [2]:
#reshaping of arrays
import numpy as np
grid= np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
x=np.array([1,2,3])
#row vector via reshape 
x.reshape((1,3))

array([[1, 2, 3]])

In [4]:
#row vector via new axis
x[np.newaxis, :]

array([[1, 2, 3]])

In [5]:
#column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [6]:
#column vector via newaxis
x[: ,np.newaxis]

array([[1],
       [2],
       [3]])

In [8]:
#array concatenation and splitting
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [9]:
z=[99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [14]:
grid=np.array([[1,2,3],
             [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
#concatenate along its second axis(zero indexed)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [17]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])
#vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [19]:
#horizontally stack thre arrays
y = np.array([[99],
          [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [26]:
#splitting of arrays
x=[1,2,3,99,99,3,2,1] 
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [22]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [27]:
left,right=np.hsplit(grid,[2])
print(right)
print(left)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
